language: java

jdk:
    - oraclejdk8

# Only ci these branches
branches:
    only:
        - master

sudo: required

cache:
    directories:
        - $HOME/.gradle

before_script:
    - mysql -e 'CREATE DATABASE rodbate CHARACTER SET = utf8;'
    - gradle flywayMigrate -Pflyway.url=jdbc:mysql://127.0.0.1:3306/rodbate -Pflyway.user=travis -Pflyway.password=

script:
    - gradle test
