language: java

jdk:
    - oraclejdk8

node_js:
- '0.11'

# Only ci these branches
branches:
    only:
        - master

sudo: required

env:
  global:
    - secure: aJ7oWMYrjC+h4FF7b7cqb7TN6/Oeo0IdCJNqvvas2JNeQi2S2hPjdoPWpcmOxR709p6N7O1ZsDoKogx78+MuFz/BUKmcOFCTid3hopD3xf8ujuoNNMfZmZTIMLYyGMcg1C2ZhoHO+uFQJJUBHr2S+ab5sqyIgfQmi7zLE9xQCkRbEuIWM9iF1Klg3lr0WSrG4nQdF0bWxpK6APiyDQ/zz8mq6Uw6Edodr4zIpkLz2Byg+LbrezWbm9SZi9sXAPkdAbppgruxpVbEnkJ0wpxdlesf+F8uSggBeZQGazVZgrKdF19SPcWbhMLOMkMo1wb4pO7IPgvMrTk5p52WawumiIMCFO28EmXetlPqgjH9F5B13+mL43hXewB4C4+ryGIITa4J3qC+SQ3d+aUM+mJHSrenSuYQ/Pas70Iyjz2x21ZCnyPydF7tTZBcS5+O2b34tZBNvTq8zIFS+Oq8QNqvngl8QDuY9Q5n+2+DMVEnb2Sda/SdnP8cAvW3VqP85jWk8N1BFUCgDrMf6ak2VuFDjo1GWLiyA6fp99NNLl4Hsx6c/9ZTLF9lddDTf2kudHWqlgm1fV9uatMvheb69WGhOeBi5HhL7yAu9BMv50spXABpI6Yb1dsSH4M6IyD7WUoHjgYf5u0xWNxL6oJ4qK+rtQLR7m8q4NXm2Axoqtuahfc=
    - secure: NhgfIkLg/ChFMOuUeG43nGUKgPAbSbyC0Mxrksl/XBQ0aNFXFvLrZmffJemLE9jocFh1WeIK7G4hSgkdhkR4oFdZQSfNgPFifPqssi765Ow9/RBTivGJLtO1/e/Ce0v/aJH9aB8LbovjGLSut3v1/RX6FJVYfXfRoCFqJfl3Xyb1MUA8WwPM1fl5vsVF07ujpRVM5YDi7FTUoDBDyW8AEcjfz0DTnsx4RIWWYnsiIX2WPGA7B4dM10XwHRJNLS0Q2Z3W/0RPe0YEfdDW2RV8xamRkOoENzvz50iyn8jL9DpUKOkKiQdmmgaARBGhF9PRtHQDf4yiHKEMZovbLO2Cm8BAzWdXtZELMPSs+mVBZRsKN/LtJCjsf83oP8p8fCX4E7XqLhb9bwllcGtqcgJXsKbOJv4U3HFYXad5GAmjW5dfkvq9hArJObNDp2b1jqqrT4tW6ebGmnrjDc1wgChTEQcuz4fzM8rESDLl8eUDyR+bh+ToHmI5MYLv4ApK0WyQpzR2XceXzfYB0+yhfgJZ6nX6kmsl3FK9gFQcpvAQsZ70exeeUoFR/TKC4+Wnsrxr+P984u6J7Psq0LoDALQKquEQH4zfUeezkbWYlw89qFm0L2bY3MeU02w/JPEFbJ70Qs9MzLbm/GHp87LsKfKF2P4kAkALTbBk6sDO3BJ/Ado=


addons:
    sauce_connect: true

cache:
    directories:
        - $HOME/.gradle

before_install:
    - npm install -g npm

before_script:
    - mysql -e 'CREATE DATABASE rodbate CHARACTER SET = utf8;'
    - gradle flywayMigrate -Pflyway.url=jdbc:mysql://127.0.0.1:3306/rodbate -Pflyway.user=travis -Pflyway.password=
    - npm install -g karma-cli

script:
    - gradle check -Dspring.profiles.active=travis



