language: java

jdk:
    - oraclejdk8

# Only ci these branches
branches:
    only:
        - master

services:
    - redis-server

cache:
    directories:
        - $HOME/.gradle

before_install:
    - git submodule update --init --recursive

before_script:
    - mysql -e 'CREATE DATABASE test CHARACTER SET = utf8;'
    - gradle -Pflyway.url=jdbc:mysql://127.0.0.1:3306/test flywayMigrate -Pflyway.user=root

script:
    - gradle javadoc
    - gradle check -Dspring.profiles.active=travis
